"""Smoke test client for the AI news journalist MCP server.

Run the server in one terminal:

    uv run python src/ai_news_journalist/mcp_server/journalist_server.py

Then run this client from another terminal:

    MCP_SERVER_URL=http://127.0.0.1:9002/sse uv run python tests/smoke_journalist_mcp.py

This client avoids BigQuery calls and tests the MCP connection with the dossier
tools only.
"""

from __future__ import annotations

import os

import anyio
from mcp import ClientSession
from mcp.client.sse import sse_client


def _server_url() -> str:
    return os.getenv("MCP_SERVER_URL", "http://127.0.0.1:9002/sse")


def _print_tool_result(label: str, result) -> None:
    print(f"\n{label}")
    if getattr(result, "isError", False):
        print("Error")
        return

    for block in getattr(result, "content", []):
        text = getattr(block, "text", None)
        if text:
            print(text)


async def main() -> None:
    async with sse_client(_server_url()) as streams:
        async with ClientSession(*streams) as session:
            await session.initialize()

            tools = await session.list_tools()
            print("Available tools:", ", ".join(tool.name for tool in tools.tools))

            save_result = await session.call_tool(
                "save_dossier",
                {
                    "title": "MCP smoke test dossier",
                    "markdown": "This dossier was generated by the MCP smoke test.",
                    "metadata": {"source": "tests/smoke_journalist_mcp.py"},
                },
            )
            _print_tool_result("save_dossier", save_result)

            list_result = await session.call_tool("list_dossiers", {})
            _print_tool_result("list_dossiers", list_result)


if __name__ == "__main__":
    anyio.run(main)
